### 9.4    破译大篇幅错误信息

普通的编译错误一般都很简明扼要。例如，当编译器报告 “`class X has no member 'fun'`” 时，找出我们代码中的错误通常不会太难（例如，我们可能错误地把 `run` 输入为了 `fun`）。但是模板不是这样。让我们看一些例子。

##### 简单的类型不匹配

考虑下面的使用了 C++ 标准库的相对简单的例子：

*basics/errornovel1.cpp*

```c++
#include <string>
#include <map>
#include <algorithm>

int main()
{
  std::map<std::string,double> coll;
  ...
  // 找到 coll 中首个不为空的字符串
  auto pos = std::find_if (coll.begin(), coll.end(),
                           [] (std::string const& s) {
                             return s != "";
                           });
}
```

它包含一个很小的错误：在用于找到集合中首个匹配字符串的 lambda 中，我们检查给定的字符串。但是，map 中的元素是键/值对，因此我们应该期望得到 `std::pair<std::string const, double>`。

一个流行的 GNU C++ 编译器版本报告了以下错误：

```
1  In file included from /cygdrive/p/gcc/gcc61-include/bits/stl_algobase.h:71:0,
2                   from /cygdrive/p/gcc/gcc61-include/bits/char_traits.h:39,
3                   from /cygdrive/p/gcc/gcc61-include/string:40,
4                   from errornovel1.cpp:1:
5  /cygdrive/p/gcc/gcc61-include/bits/predefined_ops.h: In instantiation of 'bool __gnu_cxx::__ops::_Iter_pred<_Predicate>::operator()(_Iterator) [with _Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, double> >; _Predicate = main()::<lambda(const string&)>]':
6  /cygdrive/p/gcc/gcc61-include/bits/stl_algo.h:104:42:   required from '_InputIterator std::__find_if(_InputIterator, _InputIterator, _Predicate, std::input_iterator_tag) [with _InputIterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, double> >; _Predicate = __gnu_cxx::__ops::_Iter_pred<main()::<lambda(const string&)> >]'
7  /cygdrive/p/gcc/gcc61—inc1ude/bits/stl_algo.h:161:23:   required from '_Iterator std::__find_if(_Iterator, _Iterator, _Predicate) [with _Iterator = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, double> >; _Predicate = __gun_cxx::__ops::_Iter_pred<main()::<lambda(const string&)> >]'
8  /cygdrive/p/gcc/gcc61—inc1ude/bits/stl_a1go·h:3824:28:   required from '_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, double> >; _Predicate = main()::<lambda(const string&)>]'
9  errornovel1.cpp:13:29:   required from here
10 /cygdrive/p/gcc/gcc61—inc1ude/bits/predefined_ops.h:234:11: error: no match for call to '(main()::<lambda(const string&)>) (std::pair<const std::__cxx11::basic_string<char>, double>&)'
11   { return bool(_M_pred(*__it)); }
12            ^~~~~~~~~~~~~~~~~~~~
13 /cygdrive/p/gcc/gcc61—inc1ude/bits/predefined_ops.h:234:11: note: candidate: bool (*)(const string&) {aka bool (*)(const std::__cxx11::basic_string<char>&)} <conversion>
14 /cygdrive/p/gcc/gcc61—inc1ude/bits/predefined_ops.h:234:11: note:   candidate expects 2 arguments, 2 provided
15 errornovel1.cpp:11:52: note: candidate: main()::<lambda(const string&)>
16                             [] (std::string const& s) {
17                                                     ^
18 errornovel1.cpp:11:52: note:   no known conversion for argument 1 from 'std::pair<const std::__cxx11::basic_string<char>, double>' to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
```

像这样的消息一开始看起来更像是小说而不是诊断。它也可以压倒性地劝退模板用户的新手。然而，通过一些实践，像这样的消息变得可以管理，并且错误至少相对容易定位。

错误消息的第一部分表示在内部的 `predefined_ops.h` 头文件内有一个函数模板实例发生了错误，该头文件通过各种其它头文件从 `errornovel1.cpp` 中被包含。在当前行以及后面的几行中，编译器报告了什么被实例化以及用了怎样的实参实例化。在本例中，这些都始于以 `errornovel1.cpp` 的第 13 行结尾的语句，即：

```c++
auto pos = std::find_if (coll.begin(), coll.end(),
                         [] (std::string const& s) {
                           return s != "";
                         });
```

这导致在 `stl.algo.h` 头文件的 115 行的 `find_if` 模板的实例化，其代码

```c++
_IIter std::find_if(_IIter, _IIter, _Predicate)
```

由

```
_IIter = std::_Rb_tree_iterator<std::pair<const std::__cxx11::basic_string<char>, double> >
_Predicate = main()::<lambda(const string&)>
```

实例化。

编译器报告了所有的这些，以防我们只是不期望所有的这些模板都被实例化。这允许我们确定导致实例化的事件链条。

但是，在我们的例子中，我们愿意相信所有类型的模板都需要被实例化，我们只是想知道为什么这不起作用。这个信息出现在错误信息的最后一段：这一部分报告 “`no match for call`” 表示无法解析函数调用，因为实参和形参的类型不匹配。它列出了要调用的

```
(main()::<lambda(const string&)>) (std::pair<const std::__cxx11::basic_string<char>, double>&)
```

以及引起调用的代码：

```c++
{ return bool(_M_pred(*__it)); }
```

此外，在这后面包含 “`note:   candidate:`” 的行解释了有一个候选的类型期望 `const string&`，该候选函数在 `errornovel1.cpp` 的第 11 行，定义为 lambda `[] (std::string const& s)`，并带有该候选函数不合适的原因：

```
no known conversion for argument 1 from 'std::pair<const std::__cxx11::basic_string<char>, double>' to 'const string&' {aka 'const std::__cxx11::basic_string<char>&'}
```

其描述了我们存在的问题。

毫无疑问错误信息可以变得更好。实际的问题可以在实例化前给出，而不是使用像 `std::__cxx11::basic_string<char>` 这样的完全展开的模板实例化名字，使用 `std::string` 可能就够了。但是，诊断中的所有信息都可能在一些情况下有用，这也是事实。因此，其它编译器提供类似的信息也就不足为奇了（尽管有些使用了提到的结构化技术）。

例如，Visual C++ 编译器输出了这些：

```
1  c:\tools_root\cl\inc\algorithm(166): error C2664: 'bool main::<lambda_b863c1c7cd07048816f454330789acb4>::operator ()(const std::string &) const”: cannot convert argument 1 from 'std::pair<const _Kty,_Ty>' to 'const std::string &'
2          with
3          [
4              _Kty=std::string,
5              _Ty=double
6          ]
7  c:\tools_root\cl\inc\algorithm(166): note: Reason: cannot convert from 'std::pair<const _Kty,_Ty' to 'const std::string'
8          with
9          [
10             _Kty=std::string,
11             _Ty=double
12         ]
13 c:\tools_root\cl\inc\algorithm(166): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
14 c:\tools_root\cl\inc\algorithm(177): note: see reference to function template instantiation '_InIt std::_Find_if_unchecked<std::_Tree_unchecked_iterator<_Mytree>,_Pr>(_InIt,_Init,_Pr &)' being compiled
15         with
16         [
17             _InIt=std::_Tree_unchecked_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,double>>>>,
18             _Mytree=std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,double>>>,
19             _Pr=main::<lambda_b863c1c7cd07048816f454330789acb4>
20         ]
21 main.cpp(13): note: see reference to function template instantiation '_InIt std::find_if<std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const _Kty,_Ty>>>>,main::<lambda_b863c1c7cd07048816f454330789acb4>>(_InIt,_InIt,_Pr)' being compiled
22         with
23         [
24             _InIt=std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<const std::string,double>>>>,
25             _Kty=std::string,
26             _Ty=double,
27             _Pr=main::<lambda_b863c1c7cd07048816f454330789acb4>
28         ]
```

这里我们再次提供了实例化的链条，并带有信息告诉我们哪些参数实例化了什么内容以及代码的位置，并且我们见到了两次：我们

```
cannot convert from 'std::pair<const _Kty,_Ty' to 'const std::string'
with
[
    _Kty=std::string,
    _Ty=double
]
```

##### 在一些编译器上缺失 `const`

不幸的时，有时可能某段泛型代码仅对某些编译器有问题。考虑下面的例子：

*basics/errornovel2.cpp*

```c++
#include <string>
#include <unordered_set>

class Customer
{
  private:
    std::string name;
  public:
    Customer (std::string const& n)
     : name(n) {
    }
    std::string getName() const {
      return name;
    }
};
int main()
{
  // 提供我们自己的哈希函数
  struct MyCustomerHash {
    // 注意：缺少 const 只有在 g++ 和 clang 上是错误：
    std::size_t operator() (Customer const& c) {
      return std::hash<std::string>()(c.getName());
    }
  };
    
  // 并将其用于 Customers 的哈希表
  std::unordered_set<Customer,MyCustomerHash> coll;
  ...
}
```

在 Visual Studio 2013 或 2015 上，代码能按期望编译。但是，在 g++ 或 clang 上，该代码会导致重大的错误信息。例如，在 g++ 6.1 上，第一个错误信息是这样的：

```
1  In file included from /cygdrive/p/gcc/gcc61-include/bits/hashtable.h:35:0,
2                   from /cygdrive/p/gcc/gcc61-include/unordered_set:47,
3                   from errornovel2.cpp:2:
4  /cygdrive/p/gcc/gcc61-include/bits/hashtable_policy.h: In instantiation of 'struct std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash>':
5  /cygdrive/p/gcc/gcc61-include/type_traits:143:12:   required from 'struct std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> >'
6  /cygdrive/p/gcc/gcc61-include/type_traits:154:38:   required from 'struct std::__not_<std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> > >'
7  /cygdrive/p/gcc/gcc61-include/bits/unordered_set.h:95:63:   required from 'class std::unordered_set<Customer, main()::MyCustomerHash>'
8  errornovel2.cpp:28:47:   required from here
9  /cygdrive/p/gcc/gcc61-include/bits/hashtable_policy.h:85:34: error: no match for call to '(const main()::MyCustomerHash) (const Customer&)'
10   noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
11            ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
12 errornovel12.cpp:22:17: note: candidate: std::size_t main()::MyCustomerHash::operator()(const Customer&) <near match>
13      std::size_t operator() (Customer const& c) {
14                  ^~~~~~~~
15 errornovel2.cpp:22:17: note:   passing 'const main()::MyCustomerHash*' as 'this' argument discards qualifiers
```

紧跟着超过 20 个其它的错误信息：

```
17 In file included from /cygdrive/p/gcc/gcc61-include/bits/move.h:57:0,
18                  from /cygdrive/p/gcc/gcc61-include/bits/stl_pair.h:59,
19                  from /cygdrive/p/gcc/gcc61-include/bits/stl_algobase.h:64,
20                  from /cygdrive/p/gcc/gcc61-include/bits/char_traits.h:39,
21                  from /cygdrive/p/gcc/gcc61-include/string:40,
22                  from errornovel2.cpp:1:
23 /cygdrive/p/gcc/gcc61-include/type_traits: In instantiation of 'struct std::__not_<std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> > >':
24 /cygdrive/p/gcc/gcc61-include/bits/unordered_set.h:95:63:   required from 'class std::unordered_set<Customer, main()::MyCustomerHash>'
25 errornovel2.cpp:28:47:   required from here
26 /cygdrive/p/gcc/gcc61-include/type_traits:154:38: error: 'value' is not a member of 'std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> >'
27      : public integral_constant<bool, !_Pp::value>
28                                       ^~~~
29 In file included from /cygdrive/p/gcc/gcc61-include/unordered_set:48:0,
30                  from errornovel2.cpp:2:
31 /cygdrive/p/gcc/gcc61-include/bits/unordered_set.h: In instantiation of 'class std::unordered_set<Customer, main()::MyCustomerHash>':
32 errornovel2.cpp:28:47:   required from here
33 /cygdrive/p/gcc/gcc61-include/bits/unordered_set.h:95:63: error: 'value' is not a member of 'std::__not_<std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> > >'
34        typedef __uset_hashtable<_Value, _Hash, _Pred, _Alloc>  _Hashtable;
35                                                                ^~~~~~~~~~
36 /cygdrive/p/gcc/gcc61-include/bits/unordered_set.h:102:45: error: 'value' is not a member of 'std::__not_<std::__and_<std::__is_fast_hash<main()::MyCustomerHash>, std::__detail::__is_noexcept_hash<Customer, main()::MyCustomerHash> > >'
37        typedef typename _Hashtable::key_type key_type;
38                                              ^~~~~~~~
...
```

同样，错误信息很难阅读（甚至于找到每条信息的开始和结束都是难题）。本质是，在由

```c++
std::unordered_set<Customer,MyCustomerHash> coll;
```

需要的 `std::unordered_set<>` 的实例化中，深入到头文件 `hashtable_policy.h`，在实例化

```c++
noexcept(declval<const _Hash&>()(declval<const _Key&>()))
```

时，没有对

```c++
const main()::MyCustomerHash (const Customer&)
```

的调用的匹配（`declval<const _Hash&>()` 是一个类型为 `main()::MyCustomerHash` 的表达式）。一个可能的 “接近的匹配” 的候选函数是

```c++
std::size_t main()::MyCustomerHash::operator()(const Customer&)
```

其被声明为

```c++
std::size_t operator() (Customer const& c) {
            ^~~~~~~~
```

并且最后一个注释描述了和这个问题有关的内容：

```
passing 'const main()::MyCustomerHash*' as 'this' argument discards qualifiers
```

你能看出问题所在吗？`std::unorderset` 类模板的实现要求哈希对象的函数调用运算符是一个 `const` 成员函数（见原书 159 页 11.1.1 节）。当不满足这一情况时，算法内部就会出现错误。

所有其它错误从第一个错误级联，并在简单地为哈希函数运算符添加了 `const` 限定符后消失：

```c++
std::size_t operator() (const Customer& c) const {
  ...
}
```

Clang 3.9 在第一条错误信息的末尾给出了较好的提示，即哈希函数的 `operator()` 没有被标记为 `const`：

```
...
errornovel2.cpp:28:47: note: in instantiation of template class 'std::unordered_set<Customer, MyCustomerHash, std::equal_to<Customer>, std::allocator<Customer> >' requested here
  std::unordered_set<Customer,MyCustomerHash> coll;
                                              ^

errornovel2.cpp:22:17: note: candidate function not viable: 'this' argument has type 'const MyCustomerHash', but method is not marked const
    std::size_t operator() (const Customer& c) {
                ^
```

注意 clang 在这里提到了类似于 `std::allocator<Customer>` 的默认模板参数，而 gcc 跳过了它们。

正如你所见，有多个编译器来测试你的代码通常很有帮助。这不仅可以帮助你编写更具有可移植性的代码，而且当一个编译器产生特别难以理解的错误信息时，另一个编译器可能会提供更多帮助。